{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ultraschemer.microweb",
    "module": "microweb",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "eyialgp3hrcrjnv52cpbzd6aiy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "20.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "net.sf.oval",
          "module": "oval",
          "version": {
            "requires": "1.90"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-log4j12",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.0.Final"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.30"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.littleshoot",
          "module": "littleproxy",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "microweb-0.5.0.jar",
          "url": "microweb-0.5.0.jar",
          "size": 155441,
          "sha512": "f023d5a1934fabad900a7e72af4199a35ba49398c5cf0e1529adad20ec872c49187e7c21e13d472236d78cd627d98cdb483101ac9a5e9beac8567814bd2e6b2f",
          "sha256": "f240c1d01b83a886df257dc40008bc56ef1d442825bbe9a4c1cbad1cc6fb2531",
          "sha1": "a2439ee5c2c0e0c89df624432983a6e6f9604477",
          "md5": "a9b0efc5c7249674466b58c2fc13d1f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "20.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "net.sf.oval",
          "module": "oval",
          "version": {
            "requires": "1.90"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-log4j12",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.0.Final"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.30"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.littleshoot",
          "module": "littleproxy",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "microweb-0.5.0.jar",
          "url": "microweb-0.5.0.jar",
          "size": 155441,
          "sha512": "f023d5a1934fabad900a7e72af4199a35ba49398c5cf0e1529adad20ec872c49187e7c21e13d472236d78cd627d98cdb483101ac9a5e9beac8567814bd2e6b2f",
          "sha256": "f240c1d01b83a886df257dc40008bc56ef1d442825bbe9a4c1cbad1cc6fb2531",
          "sha1": "a2439ee5c2c0e0c89df624432983a6e6f9604477",
          "md5": "a9b0efc5c7249674466b58c2fc13d1f9"
        }
      ]
    }
  ]
}
