#!/bin/bash

echo "Running docker container!!!!"
FINISH=false
PIDS=""

function linger() {
  # Wait for the script be EXPLICITLY SHUT DOWN, by setting FINISH to true:
  while [ true ]; do 
    if [ "$FINISH" == "true" ]; then
      # Stop the process
      echo "Finishing entire container..."
      exit 0
    fi
    sleep 1 
  done &
  wait
}

function initialize() {
  echo "Starting..."  
  
  java -jar /usr/local/lib/microweb/microweb-all.jar run App --launcher-class=io.vertx.core.Launcher &
  
  # Maintain the script running indefinitely:
  linger
}


function finalize() {
  killall java

  # Set this script to be finished:
  FINISH=true
}

trap finalize SIGTERM
initialize

