#!/bin/bash
set -e
# set -x

ME=`dirname $0`

if [[ "${ME}" != "" ]]; then
  cd "${ME}"
fi

DIR=`pwd`

echo "Building java packages..."
echo
if [[ -z "${PGADDR}" ]]; then
  echo "Insert the Postgres address:"
  read PGADDR
fi

if [[ -z "${PGPORT}" ]]; then
  echo "Insert the Postgres port:"
  read PGPORT
fi

if [[ -z "${PGDBNAME}" ]]; then
  echo "Insert the Postgres database name:"
  read PGDBNAME
fi

if [[ -z "${PGUSER}" ]]; then
  echo "Insert the Postgres user name:"
  read PGUSER
fi

if [[ -z "${PGPASSWD}" ]]; then
  echo "Insert the Postgres user password:"
  read PGPASSWD
fi

echo "Tweaking hibernate.cfg.xml file."

sed -i.ORIGINAL "s/<property name=\"hibernate.connection.url\">.*<\/property>/<property name=\"hibernate.connection.url\">jdbc:postgresql:\/\/${PGADDR}:${PGPORT}\/${PGDBNAME}<\/property>/g" ../src/main/resources/hibernate.cfg.xml
sed -i.BAK "s/<property name=\"hibernate.connection.username\">.*<\/property>/<property name=\"hibernate.connection.username\">${PGUSER}<\/property>/g" ../src/main/resources/hibernate.cfg.xml
sed -i.BAK "s/<property name=\"hibernate.connection.password\">.*<\/property>/<property name=\"hibernate.connection.password\">${PGPASSWD}<\/property>/g" ../src/main/resources/hibernate.cfg.xml

echo "Backing up the original JPA configuration."
cp ../src/main/resources/hibernate.cfg.xml.ORIGINAL ./hibernate.cfg.xml

echo "Removing unnecessary JPA configuration files."
rm ../src/main/resources/*.BAK ../src/main/resources/*.ORIGINAL

echo "Building..."
(cd .. && gradle shadowJar)

cp ../build/libs/microweb-all.jar ./microweb-all.jar

echo "Restoring original hibernate.cfg.xml file."
mv hibernate.cfg.xml ../src/main/resources/hibernate.cfg.xml

echo "Building development containers..."

set +e
docker stop -t 100 microweb
dos2unix dev-init
set -e

docker build --rm -t microweb-base .

rm microweb-all.jar
