#!/bin/bash
set -e

ME=`dirname $0`
DIR=$1

if [[ "${ME}" != "" ]]; then
  cd "${ME}"
fi

if [[ "${DIR}" = "" ]]; then
  DIR=`pwd`
fi

DIR=/`pwd`/src
docker run -d --name=microweb --rm=true -p 48080:48080 --memory="256m" --memory-swap="256m" --memory-swappiness=0 -it microweb-base
