{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ultraschemer.microweb",
    "module": "microweb",
    "version": "0.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "cgbzcfhoxvauvcalsty4bmvcpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "20.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "net.sf.oval",
          "module": "oval",
          "version": {
            "requires": "1.90"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-log4j12",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.0.Final"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.30"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.littleshoot",
          "module": "littleproxy",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "microweb-0.6.5.jar",
          "url": "microweb-0.6.5.jar",
          "size": 158158,
          "sha512": "dcd78b1b5e5812e8d4771dad68ea39f6fc58193482ab98094de3325480e9a34cdefbcf2b22ab525b5a0255ac35db7526c5bf1ebeae19ef0f415876e3137eba82",
          "sha256": "b482628d816c191645872999abc95dbafecac062ce7de734765ab4368d3f7c10",
          "sha1": "8605ac7ccfc1399875f057a497c56f49263d41f5",
          "md5": "22a3fc36dcdf8e2713147fe55fb0fe19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "20.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "net.sf.oval",
          "module": "oval",
          "version": {
            "requires": "1.90"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-log4j12",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.0.Final"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.30"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.littleshoot",
          "module": "littleproxy",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "microweb-0.6.5.jar",
          "url": "microweb-0.6.5.jar",
          "size": 158158,
          "sha512": "dcd78b1b5e5812e8d4771dad68ea39f6fc58193482ab98094de3325480e9a34cdefbcf2b22ab525b5a0255ac35db7526c5bf1ebeae19ef0f415876e3137eba82",
          "sha256": "b482628d816c191645872999abc95dbafecac062ce7de734765ab4368d3f7c10",
          "sha1": "8605ac7ccfc1399875f057a497c56f49263d41f5",
          "md5": "22a3fc36dcdf8e2713147fe55fb0fe19"
        }
      ]
    }
  ]
}
