{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ultraschemer.microweb",
    "module": "microweb",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "btffbfq4qrhuzaiar6326k3zum"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "20.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "net.sf.oval",
          "module": "oval",
          "version": {
            "requires": "1.90"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-log4j12",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.0.Final"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.30"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.littleshoot",
          "module": "littleproxy",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "microweb-0.4.0.jar",
          "url": "microweb-0.4.0.jar",
          "size": 154996,
          "sha512": "1d64a5ef834a00c1d337e7b625bd9422c38463b2288159c6c349431f5f97e9a684f93f55b539a7a844271bfd182f2d67fd84462577711b40b5a6eff712e8f7d8",
          "sha256": "537c644994de10e19d7488e3697bf530c5f08d81aaab458ede0b9abd8d025828",
          "sha1": "19bae02ab96e9fa66e81723bb7382028088f21c5",
          "md5": "c21418a782e1345b2d3d8b0dd99a0f28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "20.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "net.sf.oval",
          "module": "oval",
          "version": {
            "requires": "1.90"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-log4j12",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.0.Final"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.30"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.littleshoot",
          "module": "littleproxy",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "microweb-0.4.0.jar",
          "url": "microweb-0.4.0.jar",
          "size": 154996,
          "sha512": "1d64a5ef834a00c1d337e7b625bd9422c38463b2288159c6c349431f5f97e9a684f93f55b539a7a844271bfd182f2d67fd84462577711b40b5a6eff712e8f7d8",
          "sha256": "537c644994de10e19d7488e3697bf530c5f08d81aaab458ede0b9abd8d025828",
          "sha1": "19bae02ab96e9fa66e81723bb7382028088f21c5",
          "md5": "c21418a782e1345b2d3d8b0dd99a0f28"
        }
      ]
    }
  ]
}
